[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
simple_counter = "HYe3Y2gwHWxw6L981JEQokpZJon5Eqd9Tp4kQXjJhxnB"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[dependencies]
anchor-lang = "0.26.0" # Or the latest version
